### ISSUE TITLE
Breaks all extension settings in the right settings panel

### ISSUE THREAD

**Issue by LenAnderson** [XanadusWorks/SillyTavern-Dialogue-Colorizer#3]
See also #2 

At about line 479 in index.js you replace the `innerHTML` of `#extension_settings2` thereby breaking all other extension's settings menus. You should always use DOM operations when changing content of elements that are not 100% under your control (where you can deal with all side effects).

Just `.append` your settings element instead of modifying the whole HTML, please.

I've noticed a couple more `.innerHTML` calls in your script, but have not checked if they have similar side effects. Just keep in mind that it is dangerous to use.

**Comment by XanadusWorks** [comment]
Ouch, thanks for the heads-up! I was using `append` originally and changed it when refactoring for some reason - don't remember why - and assumed `+=` had the same behavior. Fixed in commit [83e1dcc](https://github.com/XanadusWorks/SillyTavern-Dialogue-Colorizer/commit/83e1dcc6d944322aafc6151d544d5b7436070d53).

Other uses of `innerHTML` target only elements created by the extension.
